site_name: Tris Documentation

theme:
    name: "material"

    features:
        - navigation.tabs
        - search.suggest
        - search.share

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: material/telescope

    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

extra_css:
    - stylesheets/style.css

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - md_in_html
    - pymdownx.tabbed:
          alternate_style: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Library:
        - Installation: library/installation.md
        - "Input/Output": library/io.md

plugins:
    - search

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/three-body-analysis/codebase

copyright: Copyright &copy; 2023 Three Body Analysis Team
